DbNetSuiteCore.Samples/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DbNetSuiteCoreSamples.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

DbNetSuiteCore.Samples/Pages/Explore.cshtml.cs
using DbNetSuiteCore.Enums;
using DbNetSuiteCore.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DbNetSuiteCoreSamples.Pages;

public class ExploreModel : IndexModel
{
    public List<DataSourceType> DataSourceTypes => new List<DataSourceType> { DataSourceType.SQLite, DataSourceType.MSSQL, DataSourceType.MySql, DataSourceType.PostgreSql, DataSourceType.Oracle, DataSourceType.MongoDB };
    public List<SelectListItem> Tables { get; set; } = new List<SelectListItem>();
    public List<SelectListItem> Databases { get; set; } = new List<SelectListItem>();
    public List<SelectListItem> Connections { get; set; } = new List<SelectListItem>();
    public List<SelectListItem> DataSourceTypeItems => DataSourceTypes.Select(x => new SelectListItem(x.ToString(), x.ToString())).ToList();
    public List<SelectListItem> ControlTypes { get; set; } = new List<SelectListItem>();

    public DataSourceType DataSourceType => (DataSourceType)Enum.Parse(typeof(DataSourceType), DataSourceTypeName);

    [BindProperty]
    public string DataSourceTypeName { get; set; } = string.Empty;
    [BindProperty]
    public string TableName { get; set; } = string.Empty;
    [BindProperty]
    public string DatabaseName { get; set; } = string.Empty;
    [BindProperty]
    public string ConnectionAlias { get; set; } = string.Empty; 
    [BindProperty]
    public string ControlType { get; set; } = string.Empty;
    public string ErrorMessage { get; set; } = string.Empty;


    private IConfiguration configuration;
    private IWebHostEnvironment? env;
    public ExploreModel(IConfiguration configuration, IWebHostEnvironment? env = null)
    {
        this.configuration = configuration;
        this.env = env;
    }
    public void OnGet()
    {
        LoadConnections();
        LoadDatabases();
        LoadTables();
        LoadControlTypes();
    }

    public void OnPost()
    {
        LoadConnections();
        LoadDatabases();
        LoadTables();
        LoadControlTypes();
    }

    public void LoadConnections()
    {
        if (string.IsNullOrEmpty(DataSourceTypeName))
        {
            DataSourceTypeName = DataSourceTypes.First().ToString();
        }

        Connections = DbHelper.GetConnections(configuration).Select(c => new SelectListItem(c.Key, c.Key)).ToList();
        if (string.IsNullOrEmpty(ConnectionAlias))
        {
            ConnectionAlias = Connections.FirstOrDefault()?.Value ?? string.Empty;
        }
    }

    public void LoadControlTypes()
    {
        List<string> controlTypes = new List<string>() { "Grid", "Form" };
        ControlTypes = controlTypes.Select(c => new SelectListItem(c, c)).ToList();
        if (string.IsNullOrEmpty(ControlType))
        {
            ControlType = controlTypes.First();
        }
    }

    public void LoadDatabases()
    {
        if (string.IsNullOrEmpty(ConnectionAlias))
        {
            return;
        }

        if (DataSourceType == DataSourceType.MongoDB)
        {
            try
            {
                Databases = DbHelper.GetDatabases(ConnectionAlias, configuration).Select(c => new SelectListItem(c, c)).ToList();
                if (string.IsNullOrEmpty(DatabaseName) || Databases.Select(d => d.Value).ToList().Contains(DatabaseName) == false)
                {
                    DatabaseName = Databases.FirstOrDefault()?.Value ?? string.Empty;
                }
            }
            catch (Exception)
            {
                TableName = string.Empty;
                ErrorMessage = $"Unable to connect to <b>{DataSourceType}</b> data source. Please check your selected connection.";
            }
        }
    }

    public void LoadTables()
    {
        if (string.IsNullOrEmpty(ConnectionAlias))
        {
            return;
        }

        try
        {
            if (DataSourceType == DataSourceType.MongoDB)
            {
                if (string.IsNullOrEmpty(DatabaseName))
                {
                    return;
                }
                Tables = DbHelper.GetTables(ConnectionAlias, configuration, DatabaseName).Select(c => new SelectListItem(c, c)).ToList();
            }
            else
            {
                Tables = DbHelper.GetTables(ConnectionAlias, DataSourceType, configuration, env).Select(c => new SelectListItem(c, c)).ToList();
            }

            if (string.IsNullOrEmpty(TableName) || Tables.Select(d => d.Value).ToList().Contains(TableName) == false)
            {
                TableName = Tables.FirstOrDefault()?.Value ?? string.Empty;
            }
        }
        catch (Exception)
        {
            Tables = new List<SelectListItem>();
        }

        if (Tables.Any() == false)
        {
            ErrorMessage = $"Unable to connect to <b>{DataSourceType}</b> data source. Please check your selected connection.";
            TableName = string.Empty;
        }
    }
}

DbNetSuiteCore.Samples/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DbNetSuiteCoreSamples.Pages;

public class IndexModel : PageModel
{
    public string CustomerId { get; set; } = null;
    public int? OrderId { get; set; } = null;

    public IndexModel()
    {
    }
}

DbNetSuiteCore.Samples/Pages/Resources.cshtml.cs
using DbNetSuiteCore.Enums;
using DbNetSuiteCore.Extensions;
using DbNetSuiteCore.Helpers;
using DbNetSuiteCore.Models;
using DbNetSuiteCore.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Text;
using System.Xml.Linq;

namespace DbNetSuiteCoreSamples.Pages;

public class ResourceModel : IndexModel
{
    public List<SelectListItem> Cultures { get; set; } = new List<SelectListItem>();

    [BindProperty]
    public string Culture { get; set; } = string.Empty;
    public string CultureText => Cultures.FirstOrDefault(c => c.Value == Culture)?.Text ?? string.Empty;

    private IConfiguration configuration;
    private IWebHostEnvironment? env;
    public ResourceModel(IConfiguration configuration, IWebHostEnvironment? env = null)
    {
        this.configuration = configuration;
        this.env = env;
    }
    public void OnGet()
    {
        LoadCultures();
    }

    public void OnPost()
    {
        LoadCultures();
        DataTable resourcesTable = GetResourcesTable();
        if (resourcesTable.Rows.Count > 0)
        {
            UpdateResources();
        }
    }

    private DataTable GetResourcesTable()
    {
        using (var connection = DbHelper.GetConnection("dbnetsuitecore", DataSourceType.SQLite, configuration, env))
        {
            connection.Open();
            QueryCommandConfig query = new QueryCommandConfig() { Sql = "select * from resources where culturecode = @culturecode", Params = new Dictionary<string, object>() { { "culturecode", Culture } } };

            return DbHelper.RunQuery(query, connection);
        }
    }


    public void OnPostUpdateResources()
    {
        LoadCultures();
        UpdateResources();
    }

    private void UpdateResources()
    {
        var resources = ResourceHelper.GetAllResourceStrings();
        var cultureResources = ResourceHelper.GetAllResourceStrings(Culture);
        using (var connection = DbHelper.GetConnection("dbnetsuitecore", DataSourceType.SQLite, configuration, env))
        {
            connection.Open();

            DataTable resourcesTable = GetResourcesTable();

            foreach (string key in resources.Keys)
            {
                var match = resourcesTable.Rows.Cast<DataRow>().FirstOrDefault(x => x.Field<string>("ResourceKey") == key);

                if (match == null)
                {
                    CommandConfig insert = new CommandConfig();
                    insert.Sql = $"insert into Resources (CultureCode, ResourceKey, EnglishText) values (@CultureCode, @ResourceKey, @EnglishText)";
                    insert.Params["@CultureCode"] = Culture;
                    insert.Params["@ResourceKey"] = key;
                    insert.Params["@EnglishText"] = resources[key];

                    if (resources[key] != cultureResources[key])
                    {
                        insert.Params["@CultureText"] = cultureResources[key];
                    }

                    using (IDbCommand command = DbHelper.ConfigureCommand(insert, connection, CommandType.Text))
                    {
                        ((DbCommand)command).ExecuteNonQuery();
                    }
                }
            }

        }
    }


    public void LoadCultures()
    {
        Cultures = CultureInfo.GetCultures(CultureTypes.NeutralCultures).OrderBy(c => c.DisplayName).Select(c => new SelectListItem(c.DisplayName, c.Name)).ToList();
        if (string.IsNullOrEmpty(Culture))
        {
            Culture = Cultures.FirstOrDefault()?.Value ?? string.Empty;
        }
    }

    public FileResult OnPostDownloadResx()
    {
        DataTable resourcesTable = GetResourcesTable();

        XElement root = new XElement("root");
        XNamespace xml = "http://www.w3.org/XML/1998/namespace";

        foreach (DataRow dataRow in resourcesTable.Rows.Cast<DataRow>())
        {
            var spaceAttr = new XAttribute(xml + "space", "preserve");
            XElement dataElement = new XElement("data", new XAttribute("name", dataRow["ResourceKey"]), spaceAttr,
            new XElement("value", dataRow["CultureText"] ?? String.Empty));
            root.Add(dataElement);
        }

        return File(Encoding.UTF8.GetBytes(root.ToString()), "application/resx", $"strings.{Culture}.resx");
    }
}

DbNetSuiteCore.Samples/Pages/Explore.cshtml
@page
@{
    Layout = "_layout";
}
@model DbNetSuiteCoreSamples.Pages.ExploreModel
@using DbNetSuiteCore.Enums
@using DbNetSuiteCore.Models
@using Microsoft.AspNetCore.Http
@using System.Data
@using System.Text.RegularExpressions
@using DbNetSuiteCore.Helpers
@using DbNetSuiteCore.Extensions

@section Title
{
    <p>Want to see how DbNetSuiteCore can present your data ? Simply add a connection to your data source the <b>ConnectionStrings</b> section in the <b>appsettings.json</b> file and you will then be be able to select that connection below.</p>
}

@{
    <div style="padding:20px">
        <form method="post">
            <div class="d-flex flex-row align-items-center" style="gap:10px">
                <div>Connection</div>
                <div>
                    <select class="form-select" asp-for="@Model.ConnectionAlias" asp-items="Model.Connections" onchange="this.form.submit()"></select>
                </div>
                <div>Data Source Type</div>
                <div>
                    <select class="form-select" asp-for="@Model.DataSourceTypeName" asp-items="Model.DataSourceTypeItems" onchange="this.form.submit()"></select>
                </div>
                @if (Model.DataSourceTypeName == DataSourceType.MongoDB.ToString())
                {
                    <div>Database</div>
                    <div>
                        <select class="form-select" asp-for="@Model.DatabaseName" asp-items="Model.Databases" onchange="this.form.submit()"></select>
                    </div>
                }
                <div>Table/View</div>
                <div>
                    <select class="form-select" asp-for="@Model.TableName" asp-items="Model.Tables" onchange="this.form.submit()"></select>
                </div>
                <div>Control Type</div>
                <div>
                    <select class="form-select" asp-for="@Model.ControlType" asp-items="Model.ControlTypes" onchange="this.form.submit()"></select>
                </div>
            </div>
        </form>

        <div style="margin-top:10px">
            @{
                if (string.IsNullOrEmpty(Model.TableName) == false)
                {
                    if (Model.ControlType == "Grid")
                    {
                        GridModel gridModel = new GridModel(Model.DataSourceType, Model.ConnectionAlias, Model.TableName) { DatabaseName = Model.DatabaseName, OptimizeForLargeDataset = true };
                        gridModel.ClientEvents[GridClientEvent.FileDownload] = "setFileName";
                        @(await DbNetSuiteCore.Control.Create(HttpContext).Render(gridModel))
                    }
                    else
                    {
                        FormModel formModel = new FormModel(Model.DataSourceType, Model.ConnectionAlias, Model.TableName) { DatabaseName = Model.DatabaseName, QueryLimit = 500, Insert = true, Delete = true };
                        @(await DbNetSuiteCore.Control.Create(HttpContext).Render(formModel))
                    }
                }

                if (string.IsNullOrEmpty(Model.ErrorMessage) == false)
                {
                    <div class="alert alert-danger" role="alert">@Html.Raw(Model.ErrorMessage)</div>
                }
            }
        </div>
    </div>
}


@section Scripts {
    <script>
        function setFileName(sender, args) {
            args.link.download = "@(CleanTableName(Model.TableName))." + args.extension
        }

    </script>
}
@functions
{
    string CleanTableName(string tableName)
    {
        if (string.IsNullOrEmpty(tableName) == false)
        {
            Regex rgx = new Regex(@"[^a-zA-Z0-9_]");
            tableName = rgx.Replace(tableName.Split(".").Last(), "");
        }

        return tableName;
    }
}

DbNetSuiteCore.Samples/Pages/Index.cshtml
@page
@using DbNetSuiteCore.Enums
@using DbNetSuiteCore.Models

@model DbNetSuiteCore.Samples.ViewModels.SampleModel

@section Title
{
    <p>Welcome to the <b>DbNetSuiteCore</b> samples application. The aim is to demonstrate the capabilities of <b>DbNetSuiteCore</b> in terms of transforming data from different sources into a useable web UI. The samples menu itself uses the <b>Grid</b> control to pull information from the file system to create a dynamic menu from the project Razor pages folder.</p> 
}

@section Control {
@{
        var components = new List<string> { "Grid", "Form", "Select", "Tree" };

        <div class="d-flex justify-content-between align-items-start">
            <ul class="nav nav-tabs" id="componentTabs" role="tablist">
                @foreach (string component in components)
                {
                    <li class="nav-item" role="presentation">
                        <button class="nav-link @(component == components.First() ? "active" : string.Empty)" id="@(component)-tab" data-bs-toggle="tab" data-bs-target="#@(component)" type="button" role="tab" aria-controls="home" aria-selected="true">Razor @(component) Samples</button>
                    </li>
                }
            </ul>
            <a class="btn btn-outline-primary btn-sm ms-2 pull-right" href="/home/index" role="button">MVC Samples</a>
        </div>
        <div class="tab-content" id="componentMenu">
            @foreach (string component in components)
            {
                <div class="tab-pane fade show @(component == components.First() ? "active" : string.Empty)" id="@(component)" role="tabpanel" aria-labelledby="@(component)-tab">
                @{
                    var columns = new List<GridColumn>()
                    {
                        new GridColumn(FileSystemColumn.Name.ToString(), "Sample"),
                        new GridColumn(FileSystemColumn.Content.ToString(), "Summary") { RegularExpression = "<p data-summary>(.*?)</p>"}
                    };
                    var samplesGrid = new GridModel(DataSourceType.FileSystem, $"../Pages/Samples/{component}")
                    {
                        FixedFilter = "(IsDirectory = 1 or Name like '%.cshtml') and Name not in ('Shared','_ViewStart.cshtml','index.cshtml','detail.cshtml', 'renderfile.cshtml')",
                        Columns = columns,
                        ToolbarPosition = ToolbarPosition.Hidden,
                        Caption = $"Razor {component} Samples",
                        RowSelection = RowSelection.None
                    };

                    samplesGrid.ClientEvents[GridClientEvent.CellTransform] = "createLink";
                    @(await DbNetSuiteCore.Control.Create(HttpContext).Render(samplesGrid))
                }

                </div>
            }
        </div>
}}
@section Scripts {
    <script type="text/javascript" class="source">
        function createLink(gridControl, args) {
            var tbody = args.cell.closest("tbody")
            var url = tbody.dataset.url.toString().toLowerCase().replace('../pages', '')

               switch (args.columnName.toLowerCase()) {
                case "name":
                    var name = args.cell.dataset.value.toString()
                    if (name.endsWith(".cshtml") && name.startsWith("_") == false) {
                        args.cell.innerHTML = `<a target='_blank' href='${window.location.origin}${url}/${name.replace(".cshtml", "")}'>${name.replace(".cshtml", "")}</a>`
                    }
                    break;
                case "content0":
                    var html = args.cell.innerHTML
                    html = html.replace(/@@RazorHelper.HelpLink\("/g, '<a style="font-weight:bold" href="https://github.com/dbnetlink/DbNetSuiteCore2/wiki/')
                    html = html.replace(/", "/g, '" target="_blank">')
                    html = html.replace(/"\)/g, '</a>')
                    args.cell.innerHTML = html;
                    break;
            }
        }
    </script>
}

DbNetSuiteCore.Samples/Pages/Resources.cshtml
@page
@{
    Layout = "_layout";
}
@model DbNetSuiteCoreSamples.Pages.ResourceModel
@using DbNetSuiteCore.Enums
@using DbNetSuiteCore.Models
@using Microsoft.AspNetCore.Http
@using System.Data
@using System.Text.RegularExpressions
@using DbNetSuiteCore.Helpers
@using DbNetSuiteCore.Extensions

@section Title
{
    <p>Want to localise DbNetSuiteCore for your own language ? You can use this page to create a translation of the strings used in DbNetSuiteCore which you can send to <b>info@dbnetlink.co.uk</b> which will then add as a resource file for your culture. Simply select your language, click <b>Update</b> then enter translations for each of the resource strings and save. Then click on <b>Download</b> to download the resource file and send it to us for inclusion in the DbNetSuiteCore package.</p>
}

@{
    <div style="padding:20px">
        <form method="post">
            <div class="d-flex flex-row align-items-center" style="gap:10px">
                <div>Language</div>
                <div>
                    <select class="form-select" asp-for="@Model.Culture" asp-items="Model.Cultures" onchange="this.form.submit()"></select>
                </div>
                <div>
                    <button type="submit" name="update" class="btn btn-primary" asp-page-handler="UpdateResources">Update</button>
                </div>
                <div>
                    <button type="submit" name="download" class="btn btn-secondary" asp-page-handler="DownloadResx">Download Resource File</button>
                </div>
            </div>
        </form>

        <div style="margin-top:10px">
            @{
                GridModel resourcesModel = new GridModel(DataSourceType.SQLite, "dbnetsuitecore", "resources") { PageSize = 100 };

                resourcesModel.Columns = new List<GridColumn>
        {
        new GridColumn("id") {DataOnly = true, PrimaryKey = true},
        new GridColumn("ResourceKey"),
        new GridColumn("EnglishText"),
        new GridColumn("CultureText", $"{Model.CultureText} Text") {FormColumn = new FormColumn(), Style = "width:600px"}
        };

                resourcesModel.FixedFilter = "CultureCode = @culturecode";
                resourcesModel.FixedFilterParameters.Add(new DbParameter("culturecode", Model.Culture));

                @(await DbNetSuiteCore.Control.Create(HttpContext).Render(resourcesModel))
            }
        </div>
    </div>
}